### PR TITLE
Fix `rotencode` parameter

### LINKED ISSUE #252: [PE-D] Exception Messages May Be Too Unspecific/General
The exception messages are correctly handled! However, they may be too unspecific and may make the user confused as to why an error is being thrown.

For example, as per the screenshot above, the exception is thrown for an "Invalid module parameter", but it may help your users understand your product better if you explain that the "moduleArgument is Too Long". This can apply to your other exceptions as well, which generally follow the same format.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: renzocanare/ped#1

### LINKED ISSUE #253: [PE-D] parameter correct but invalid
-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: JaCh23/ped#1

### PR DESCRIPTION
**Pull request by arraysius**
Fixes #252 , fixes #253

### CODE REVIEW

File: src/main/java/decodex/ui/messages/ErrorMessages.java [hunk 1]
```diff
@@ -22,7 +22,8 @@
     public static final String TOO_MANY_COMMAND_ARGUMENTS = "Too many command arguments";
     public static final String INVALID_LIST_CATEGORY = "Invalid list category";
     public static final String UNKNOWN_MODULE_NAME = "Unknown module name";
-    public static final String INVALID_MODULE_PARAMETERS = "Invalid module parameters";
+    public static final String INVALID_ROTENCODE_PARAMETER = "The rotation offset must be between -2147483648 (MIN_INT)"
+            + " and 2147483647 (MAX_INT)";
```
Comment (rizemon) [inline src/main/java/decodex/ui/messages/ErrorMessages.java:26]: Perhaps maybe include `must be an integer between...`? This is so that they do not mistakenly put floating point numbers.

File: docs/UserGuide.md [hunk 2]
```diff
@@ -97,6 +97,12 @@ This section serves to help you better understand the terminologies used in this
 4. Rotational Cipher
    1. `rotencode` - Rotates alphabetical characters by a specified integer offset
 
+| Module         | Description                                                   | Parameters                                                                                              |
+| -------------- | ------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- |
+| `base64encode` | Encodes the data using base64 format                          | N.A                                                                                                     |
+| `rotencode`    | Rotates alphabetical characters by a specified integer offset | 1. `offset`: The rotation offset.<br><br>Must be between -2147483648 (MIN_INT) and 2147483647 (MAX_INT) |
```
Comment (rizemon) [inline docs/UserGuide.md:103]: I think here instead of saying `offset`, I think we should state that is the `moduleArgument` or somewhere so that they know we are referring to `moduleArgument`.

**Review by rizemon — CHANGES_REQUESTED** [review]
Some changes.

**Review by Kair0s3 — APPROVED** [review]
Looks good

**Review by rizemon — APPROVED** [review]
LGTM
