### PR TITLE
Bug fix #1

### LINKED ISSUE #245: Convert recipe load error into single line
image

For each recipe that failed to load, they should be collated together and printed as a single string and have the `[x]` in front as well.

```
[x] Fail to be load into Decodex: failRecipe1, failRecipe2, failRecipe3 (Perhaps insufficient permissions, invalid format or unsupported module?)
```

### PR DESCRIPTION
**Pull request by Kair0s3**
Fixes #245 
And another bug address in discord instead.

### CODE REVIEW

File: src/main/java/decodex/storage/Storage.java [hunk 1]
```diff
@@ -107,8 +108,14 @@ public void loadRecipesFromDirectory(ModuleManager moduleManager, RecipeManager
...
      * @return The list of recipe File objects.
      */
-    private File[] getAllRecipeFiles() {
+    private File[] getAllRecipeFiles() throws StorageException {
         File recipeDirectory = new File(DEFAULT_RECIPE_DIRECTORY);
+
+        if (!recipeDirectory.isDirectory()) {
+            // throw error if not a valid directory.
+            throw new StorageException(ErrorMessages.INVALID_RECIPE_DIRECTORY_FILETYPE);
+        }
```
Comment (rizemon) [inline src/main/java/decodex/storage/Storage.java:117]: This is on me but when I think about it, perhaps checking if its NULL is better because this will handle if the recipeDirectory is not a directory as well as handle i/o issues (maybe issues when the os listing the files)

File: src/main/java/decodex/ui/messages/ErrorMessages.java [hunk 2]
```diff
@@ -34,4 +34,7 @@
     public static final String RECIPE_FILE_DELETE_FAILED_MESSAGE = "Failed to delete the corresponding recipe file";
     public static final String FAILED_TO_LOAD_RECIPE_FILE_MESSAGE = " failed to be loaded into Decodex";
     public static final String INVALID_RECIPE_COMMAND = "Invalid recipe command";
+    public static final String INVALID_RECIPE_DIRECTORY_FILETYPE = "The recipe folder does not seem "
+            + "to be a valid folder, but rather a file, please change it "
+            + "to ensure that you can save your recipes created properly";
```
Comment (rizemon) [inline src/main/java/decodex/ui/messages/ErrorMessages.java:39]: I think if we are going with the null approach, just give a general error here saying that failed to access `recipes` directory. Then perhaps, we could give the solution to this error within the user guide's FAQ.

File: src/main/java/decodex/ui/Ui.java [hunk 3]
```diff
@@ -230,7 +230,7 @@ public void printNewRecipeCreated(String recipeName) {
      */
     public void printFailedToLoadFromStorageMessage(ArrayList<String> failedFilesMessageList) {
         for (String failedFileMessage : failedFilesMessageList) {
-            System.out.println(failedFileMessage);
+            System.out.println(ERROR_ICON + failedFileMessage);
```
Comment (rizemon) [inline src/main/java/decodex/ui/Ui.java:233]: Perhaps add a space in between the error icon and the message?

**Review by rizemon — CHANGES_REQUESTED** [review]
Some changes

File: src/main/java/decodex/ui/messages/ErrorMessages.java (hunk 2 above)
Comment (arraysius) [reply src/main/java/decodex/ui/messages/ErrorMessages.java:39]: Agreed. Maybe a general error like `Unable to access recipe directory`.

File: src/main/java/decodex/storage/Storage.java (hunk 1 above)
Comment (arraysius) [reply src/main/java/decodex/storage/Storage.java:117]: Can consider checking existence with `recipeDirectory.exists()` as well.

File: src/main/java/decodex/storage/Storage.java [hunk 4]
```diff
@@ -107,8 +108,14 @@ public void loadRecipesFromDirectory(ModuleManager moduleManager, RecipeManager
...
+
         File[] files = recipeDirectory.listFiles();
         File[] recipeFiles = Arrays.stream(files)
```
Comment (arraysius) [inline src/main/java/decodex/storage/Storage.java:120]: Perhaps only files with the `.txt` extension should be loaded to prevent reading of unsupported file types.

**Review by arraysius — CHANGES_REQUESTED** [review]
LG for the most part. Minor improvements can be made.

**Review by rizemon — CHANGES_REQUESTED** [review]
LGTM but there is still a few `File()` constructors that have no validation after it was called. Perhaps share whats your plan with those? (Maybe purposely wait for the the program to throw IOException when read/writing content to a directory?)

File: src/main/java/decodex/storage/Storage.java [hunk 5]
```diff
@@ -109,9 +100,15 @@ public void loadRecipesFromDirectory(ModuleManager moduleManager, RecipeManager
      */
     private File[] getAllRecipeFiles() {
         File recipeDirectory = new File(DEFAULT_RECIPE_DIRECTORY);
+
         File[] files = recipeDirectory.listFiles();
+
```
Comment (rizemon) [inline src/main/java/decodex/storage/Storage.java:105]: Perhaps add a check if `listFiles()` returns null? If so, throw an exception

File: src/main/java/decodex/storage/Storage.java [hunk 6]
```diff
@@ -319,15 +266,22 @@ public void deleteRecipeFile(String recipeName) throws IOException {
...
         }
+        if (directory.isFile()) {
+            // throw error if not a valid directory.
+            String formattedErrorMessage = String.format(ErrorMessages.INVALID_DIRECTORY_ACCESS, directory);
+            throw new StorageException(formattedErrorMessage);
+        }
 
         boolean isSuccessful;
-        isSuccessful = outputDirectory.mkdir();
+        isSuccessful = directory.mkdir();
```
Comment (rizemon) [inline src/main/java/decodex/storage/Storage.java:284]: Perhaps put these on the same line?

**Review by rizemon — CHANGES_REQUESTED** [review]
A few changes

File: src/main/java/decodex/storage/Storage.java [hunk 7]
```diff
@@ -109,9 +100,15 @@ public void loadRecipesFromDirectory(ModuleManager moduleManager, RecipeManager
...
     private File[] getAllRecipeFiles() {
         File recipeDirectory = new File(DEFAULT_RECIPE_DIRECTORY);
+
         File[] files = recipeDirectory.listFiles();
+
         File[] recipeFiles = Arrays.stream(files)
                 .filter(file -> file.isFile())
+                .filter(file -> {
+                    String fileName = file.getName();
+                    return fileName.contains(RECIPE_FILE_PREFIX);
```
Comment (arraysius) [inline src/main/java/decodex/storage/Storage.java:110]: Perhaps `.endsWith()` might cover more cases than `.contains()`

**Review by arraysius — CHANGES_REQUESTED** [review]
Some minor changes

File: src/main/java/decodex/storage/Storage.java (hunk 5 above)
Comment (Kair0s3) [reply src/main/java/decodex/storage/Storage.java:105]: I feel this might be unnecessary since, if the instantiate function throws exception alr if its a file instead of directory, before it actually goes into this function.

Comment (rizemon) [reply src/main/java/decodex/storage/Storage.java:105]: Understood, did not see the earlier instantiate method.

File: src/main/java/decodex/storage/Storage.java (hunk 7 above)
Comment (rizemon) [reply src/main/java/decodex/storage/Storage.java]: Or perhaps use a regex check if we want to be much stricter? Like `^[A-Za-z0-9_]\.txt$`?

**Review by arraysius — APPROVED** [review]
LGTM

**Review by rizemon — APPROVED** [review]
LGTM
